python train_placelesion.py
--network_path
C:\Users\e.marcus\Models\vae_node21\vae_64_sigma_down_latent_16\vae_64_sigma_down_latent_16\latest_net_G.pth
--dataset_mode_train
custom_train_place_lesion
--dataset_mode
custom_train_place_lesion
--model
arrangeplacelesion
--name
vae_64_sigma_down_latent_16
--checkpoints_dir
C:\Users\e.marcus\Models\vae_node21\vae_64_sigma_down_latent_16\
--train_image_dir
C:\Users\e.marcus\PycharmProjects\challenging-nodes\datasets
--train_lesion_dir
C:\Users\e.marcus\PycharmProjects\challenging-nodes\datasets\projected\images
--validation_freq
1000
--gpu_ids
0
--niter
50
--batchSize
1
--display_freq
1
--load_from_checkpoint
--num_workers=0
--netD
deepfill
--node21_resample_count
10
--include_chexpert
--include_mimic
--D_steps_per_G
100000
--no_l1_loss